### ISSUE TITLE
Simplifying extensions/preBuild.ts

### ISSUE THREAD

**Issue by alexandrudima** [basarat/monaco#3]
@basarat 

Hi, I noticed the cool scripts you've written that allow you to build the editor out of vscode with a bit of customization. I'd like to reduce the amount of patches you need to do to get this working.

I've started with Microsoft/vscode@9c70ea130260bea84f25ff2d8dbd1b35940ccd6d

I'll try to understand some of the things you're customizing and check with you here what I think you could remove:
- [x] The `marked.mock` patch is no longer needed since quite a while (`./vscode/build/gulpfile.editor.js`).
- [x] Given Microsoft/vscode@3974c1e374db46b51cf5814d0339dd6447c915fe you can remove the patch for `./vscode/gulpfile.js`
- [ ] To install only the npm modules subset that allow for editor compilation / test-running: `npm run monaco-editor-setup` (you should be able to remove all the `package.json` massaging)

I'll update this issue as I look through what you're doing.

**Comment by basarat** [comment]
Awesome. Thanks! I know I should have reached out but didn't want to be a bother. I'll update you when I've done the required tasks and come back with any issues :heart:

**Comment by basarat** [comment]
Thanks, I've actioned the issues you pointed out and tested that markdown still works :rose:

**Comment by alexandrudima** [comment]
You should be able to remove a large portion of the script and replace it with `npm run monaco-editor-setup`. The rest of the patches seem to try to do the following:
- [ ] change some keybindings
- [ ] change some colors
- [ ] expose CommonEditorRegistry and EditorAction

We can look into adding API for defining the keybindings and for exposing the editor registry. For actions, there already is `editor.addAction()` ... Is that too limited ?

**Comment by basarat** [comment]
> (you should be able to remove all the package.json massaging)

I tried, it fails with ghooks : 

![image](https://cloud.githubusercontent.com/assets/874898/19747620/85aa1e0a-9c28-11e6-9682-25e07311e536.png)

**Comment by basarat** [comment]
Leave it with me. Working it out :rose:

**Comment by basarat** [comment]
> npm run monaco-editor-setup

Create a PR that shows the error : https://github.com/basarat/monaco/pull/6

**Comment by basarat** [comment]
Closing as its been a while. Feel free to comment if you want me to look at it again :rose:
